name: CI
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.kt'
      - '**.kts'
      - '.github/workflows/**'
      - 'gradle/wrapper/**'
      - 'gradlew'
      - 'gradlew.bat'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-with-Java-8-and-later:
    runs-on: ${{ matrix.os }}
    name: Build/Test (JDK ${{ matrix.java }}, ${{ matrix.os }})
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        java: [ 8, 17 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Build and test
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: build shadowJar

  upload-artifact:
    runs-on: ubuntu-latest
    name: Build netlog.jar
    if: github.repository == 'T-Fowl/netlog-tools' && github.ref == 'refs/heads/master'
    needs:
      - build-and-test-with-Java-8-and-later
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: build shadowJar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: netlog.jar
          path: build/libs/netlog-*-all.jar